### ISSUE TITLE
That's nice. How can I try it

### ISSUE THREAD

**Issue by juliencarponcy** [stoffelc/imageJ_play_Claire#7]
Hi,

Any docs somehwere about the install that I missed to be able to try that? 

Thanks

**Comment by stoffelc** [comment]
Hi,

This project is still at an early stage of development, so it is not possible to try it out yet.
I'll keep you updated as soon as it becomes ready for use!

Best
Claire

**Comment by NicoKiaru** [comment]
Hi @juliencarponcy this repo is archived, the new repo (which is now working, is at https://github.com/BIOP/bigdataviewer-image-loaders)

**Comment by NicoKiaru** [comment]
Cleaning issues of archived repos
